<?php

namespace AdminBundle\Repository;

/**
 * localiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class localiteRepository extends \Doctrine\ORM\EntityRepository
{
}
